packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'examples/**'
  # exclude packages end-to-end test package
  - '!packages/end-to-end/app'
  - '!packages/end-to-end/local_modules'
