packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'examples/**'
  # exclude test packages
  - '!examples/federation/integration'
  - '!packages/end-to-end/app'
  - '!packages/end-to-end/local_modules/**'
