name: End to End Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image 
        image: postgres
        # Provide env for postgres to set-up database
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gw
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.9
            
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: src/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm i

      - name: Build CLI tool
        run: pnpm build
      
      - name: Install psql
        run: apt-get update && apt-get install --yes --no-install-recommends postgresql-client

      - name: Set up PostgreSQL
        working-directory: src/packages/end-to-end
        run: PGPASSWORD=postgres pnpm setup-postgres

      - name: Create GW instance
        working-directory: src/packages/end-to-end
        run: |
          pnpm create-app

      - name: Import Chinook SQLite Database
        working-directory: src/packages/end-to-end
        run: |
          pnpm import-database-sqlite

      - name: Import Chinook Postgres SQL Database
        working-directory: src/packages/end-to-end
        run: |
          pnpm import-database-sql

      - name: Start and Test GW instance
        working-directory: src/packages/end-to-end
        timeout-minutes: 2
        run: |
          pnpm start-server &
          sleep 3 &&
          pnpm test &&
          killall node

        env:
          CI: true
