name: action-jira-linker
on: [pull_request]

jobs:
  action-jira-linker:
    runs-on: ubuntu-latest
    steps:
      - uses: exogee-technology/action-jira-linker@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-user: ${{ secrets.JIRA_USER }}
          jira-base-url: https://exogee.atlassian.net
