name: Mysql End to End Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  mysql-end-to-end-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Show mysql databases for root user
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -ppassword -e "SHOW DATABASES"

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.9

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: src/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm i

      - name: Build CLI tool
        run: pnpm build

      - name: Import Mysql Chinook Database
        working-directory: src/packages/end-to-end
        run: pnpm import-database-mysql

      - name: Start and Test Chinook instance
        working-directory: src/packages/end-to-end
        timeout-minutes: 2
        run: |
          pnpm start-server &
          sleep 3 &&
          pnpm test-mysql &&
          killall node

    env:
      CI: true
      MYSQL_PASSWORD: password
